set -g mouse on
set -g mode-keys vi
set -g status-keys vi
set -s set-clipboard on

set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -s escape-time 10
set -g focus-events on

set -s default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",screen-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode    Enter send-keys -X copy-pipe-and-cancel "pbcopy"

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
